"""Remove seller_name and review_count from competitor_products

Revision ID: 051f22e186d9
Revises: 4190fad3f8dc
Create Date: 2026-09-03 15:20:45.132270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051f22e186d9'
down_revision: Union[str, Sequence[str], None] = '4190fad3f8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor_products', 'seller_name')
    op.drop_column('competitor_products', 'review_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_products', sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('competitor_products', sa.Column('seller_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
