"""add_scraping_fields

Revision ID: 22917feae6f2
Revises: 1065dba51dd9
Create Date: 2026-09-01 16:12:39.860993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22917feae6f2'
down_revision: Union[str, Sequence[str], None] = '1065dba51dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_catalog', sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_catalog', sa.Column('scraping_status', sa.String(), server_default='NEVER_SCRAPED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_catalog', 'scraping_status')
    op.drop_column('product_catalog', 'last_scraped_at')
    # ### end Alembic commands ###
