"""update user authentication fields

Revision ID: 2fda75208eaa
Revises: 1d0d091c0d89
Create Date: 2026-08-24 20:20:53.777796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fda75208eaa'
down_revision: Union[str, Sequence[str], None] = '1d0d091c0d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name', new_column_name='retailer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'retailer_name', new_column_name='name')
    # ### end Alembic commands ###
