"""Add unique constraint to product_url

Revision ID: 4190fad3f8dc
Revises: 22917feae6f2
Create Date: 2026-09-03 12:24:12.254051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4190fad3f8dc'
down_revision: Union[str, Sequence[str], None] = '22917feae6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_price_history', sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('competitor_products', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uix_competitor_product_url', 'competitor_products', ['product_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_competitor_product_url', 'competitor_products', type_='unique')
    op.alter_column('competitor_products', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('competitor_price_history', 'scraped_at')
    # ### end Alembic commands ###
