"""remove_seller_and_review

Revision ID: c8a4015ec723
Revises: 051f22e186d9
Create Date: 2026-09-03 16:26:38.270409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a4015ec723'
down_revision: Union[str, Sequence[str], None] = '051f22e186d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_competitor_product_url'), 'competitor_products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uix_competitor_product_url'), 'competitor_products', ['product_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
