"""standardize_models

Revision ID: e77f5f74115f
Revises: 
Create Date: 2026-07-27 20:59:32.924868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e77f5f74115f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tables_with_created = ["agent_logs", "price_analysis", "product_catalog", "recommendations", "retailer_products", "users"]
    tables_with_updated = ["product_catalog", "retailer_products", "users"]
    for t in tables_with_created:
        op.execute(f"UPDATE {t} SET created_at = now() WHERE created_at IS NULL")
    for t in tables_with_updated:
        op.execute(f"UPDATE {t} SET updated_at = now() WHERE updated_at IS NULL")
    op.add_column('agent_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('agent_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('agent_logs_retailer_product_id_fkey'), 'agent_logs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_logs', 'retailer_products', ['retailer_product_id'], ['id'], ondelete='CASCADE')
    op.add_column('competitor_price_history', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('competitor_price_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('competitor_price_history_competitor_product_id_fkey'), 'competitor_price_history', type_='foreignkey')
    op.create_foreign_key(None, 'competitor_price_history', 'competitor_products', ['competitor_product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('competitor_price_history', 'recorded_date')
    op.add_column('competitor_products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('competitor_products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_competitor_products_catalog_product_id'), 'competitor_products', ['catalog_product_id'], unique=False)
    op.create_index(op.f('ix_competitor_products_platform_name'), 'competitor_products', ['platform_name'], unique=False)
    op.create_foreign_key(None, 'competitor_products', 'product_catalog', ['catalog_product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('competitor_products', 'scraped_at')
    op.add_column('price_analysis', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('price_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('price_analysis_retailer_product_id_fkey'), 'price_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'price_analysis', 'retailer_products', ['retailer_product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product_catalog', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('product_catalog', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.add_column('recommendations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('recommendations_retailer_product_id_fkey'), 'recommendations', type_='foreignkey')
    op.create_foreign_key(None, 'recommendations', 'retailer_products', ['retailer_product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('retailer_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('retailer_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('retailer_products_user_id_fkey'), 'retailer_products', type_='foreignkey')
    op.drop_constraint(op.f('retailer_products_catalog_product_id_fkey'), 'retailer_products', type_='foreignkey')
    op.create_foreign_key(None, 'retailer_products', 'product_catalog', ['catalog_product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'retailer_products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'retailer_products', type_='foreignkey')
    op.drop_constraint(None, 'retailer_products', type_='foreignkey')
    op.create_foreign_key(op.f('retailer_products_catalog_product_id_fkey'), 'retailer_products', 'product_catalog', ['catalog_product_id'], ['id'])
    op.create_foreign_key(op.f('retailer_products_user_id_fkey'), 'retailer_products', 'users', ['user_id'], ['id'])
    op.alter_column('retailer_products', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('retailer_products', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.create_foreign_key(op.f('recommendations_retailer_product_id_fkey'), 'recommendations', 'retailer_products', ['retailer_product_id'], ['id'])
    op.alter_column('recommendations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('recommendations', 'updated_at')
    op.alter_column('product_catalog', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_catalog', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'price_analysis', type_='foreignkey')
    op.create_foreign_key(op.f('price_analysis_retailer_product_id_fkey'), 'price_analysis', 'retailer_products', ['retailer_product_id'], ['id'])
    op.alter_column('price_analysis', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('price_analysis', 'updated_at')
    op.add_column('competitor_products', sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'competitor_products', type_='foreignkey')
    op.drop_index(op.f('ix_competitor_products_platform_name'), table_name='competitor_products')
    op.drop_index(op.f('ix_competitor_products_catalog_product_id'), table_name='competitor_products')
    op.drop_column('competitor_products', 'updated_at')
    op.drop_column('competitor_products', 'created_at')
    op.add_column('competitor_price_history', sa.Column('recorded_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'competitor_price_history', type_='foreignkey')
    op.create_foreign_key(op.f('competitor_price_history_competitor_product_id_fkey'), 'competitor_price_history', 'competitor_products', ['competitor_product_id'], ['id'])
    op.drop_column('competitor_price_history', 'updated_at')
    op.drop_column('competitor_price_history', 'created_at')
    op.drop_constraint(None, 'agent_logs', type_='foreignkey')
    op.create_foreign_key(op.f('agent_logs_retailer_product_id_fkey'), 'agent_logs', 'retailer_products', ['retailer_product_id'], ['id'])
    op.alter_column('agent_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('agent_logs', 'updated_at')
    # ### end Alembic commands ###
