import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
async function call(path, { token, ...options } = {}) {
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options?.headers } });
  const data = response.status === 204 ? null : await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data?.detail || 'We could not complete that request. Please try again.');
  return data;
}

function Auth({ onLogin }) {
  const [register, setRegister] = useState(false), [show, setShow] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function submit(e) {
    e.preventDefault(); setBusy(true); setError(''); const form = new FormData(e.currentTarget);
    try {
      if (register) await call('/auth/register', { method: 'POST', body: JSON.stringify({ retailer_name: form.get('name'), email: form.get('email'), business_name: form.get('business') || null, password: form.get('password') }) });
      const body = new URLSearchParams({ username: form.get('email'), password: form.get('password') });
      const response = await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body });
      const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Sign in failed. Check your email and password.'); onLogin(data.access_token);
    } catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  return <main className="auth-shell"><section className="auth-art"><div className="brand"><span className="brand-mark">P</span> pricepulse</div><div className="art-copy"><span className="eyebrow">PRICING INTELLIGENCE, IN MOTION</span><h1>Find the price<br/>that moves you <i>forward.</i></h1><p>Market context, clear recommendations, and confident decisions in one calm workspace.</p><div className="orbit"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-center">₹</div><span className="orbit-tag tag-a">Market signals</span><span className="orbit-tag tag-b">Your margin</span></div></div><span className="art-foot">Built for the next move.</span></section><section className="auth-panel"><form className="auth-form" onSubmit={submit}><span className="eyebrow">{register ? 'START YOUR WORKSPACE' : 'WELCOME BACK'}</span><h2>{register ? 'Create your account' : 'Good to see you.'}</h2><p className="muted">{register ? 'A clearer view of your market starts here.' : 'Sign in to pick up where you left off.'}</p>{register && <><label>Your name<input name="name" required autoComplete="name" placeholder="Alex Morgan"/></label><label>Business name <small>Optional</small><input name="business" placeholder="Studio or store"/></label></>}<label>Email address<input name="email" type="email" required autoComplete="email" placeholder="you@company.com"/></label><label>Password<span className="password-field"><input name="password" type={show ? 'text' : 'password'} required autoComplete={register ? 'new-password' : 'current-password'} placeholder={register ? '8+ characters, mixed case and symbol' : 'Enter your password'}/><button type="button" className="show-pass" onClick={() => setShow(!show)}>{show ? 'Hide' : 'Show'}</button></span></label>{error && <div className="error-msg" role="alert">{error}</div>}<button className="primary wide" disabled={busy}>{busy ? 'One moment…' : register ? 'Create account' : 'Sign in'} <span>↗</span></button><p className="switch-auth">{register ? 'Already have an account?' : 'New to PricePulse?'} <button type="button" onClick={() => { setRegister(!register); setError(''); }}>{register ? 'Sign in' : 'Create account'}</button></p><p className="auth-legal">Your workspace is private and protected.</p></form></section></main>;
}

function App() {
  const [token, setToken] = useState(localStorage.getItem('pp-token') || '');
  const [products, setProducts] = useState([]), [recs, setRecs] = useState([]), [selected, setSelected] = useState(null), [formOpen, setFormOpen] = useState(false);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [analysis, setAnalysis] = useState(null);
  const [chatOpen, setChatOpen] = useState(false), [question, setQuestion] = useState(''), [answer, setAnswer] = useState('');
  const recommendation = useMemo(() => recs.find(r => r.retailer_product_id === selected?.id), [recs, selected]);
  async function refresh(t = token) { const [p, r] = await Promise.all([call('/api/products', { token: t }), call('/api/recommendations', { token: t })]); setProducts(p); setRecs(r); setSelected(current => current ? p.find(x => x.id === current.id) || p[0] : p[0]); }
  useEffect(() => { if (token) { localStorage.setItem('pp-token', token); refresh().catch(e => setError(e.message)); } else localStorage.removeItem('pp-token'); }, [token]);
  async function createProduct(e) { e.preventDefault(); setBusy(true); setError(''); const f = new FormData(e.currentTarget); try { const p = await call('/api/products', { token, method: 'POST', body: JSON.stringify({ product_name: f.get('product_name'), category: f.get('category'), brand: f.get('brand'), product_details: f.get('details'), cost_price: Number(f.get('cost')), stock_quantity: Number(f.get('stock')), minimum_profit_margin: Number(f.get('margin')) }) }); setFormOpen(false); await refresh(); setSelected(p); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function analyze() { if (!selected) return; setBusy(true); setError(''); setAnalysis(null); try { const result = await call(`/api/workflow/${selected.id}/analyze`, { token, method: 'POST' }); setAnalysis(result); if (result.recommendation) await refresh(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function ask(e) { e.preventDefault(); if (!selected || !question.trim()) return; setBusy(true); setAnswer(''); try { const result = await call('/api/chat', { token, method: 'POST', body: JSON.stringify({ retailer_product_id: selected.id, question }) }); setAnswer(result.answer); } catch (e) { setAnswer(e.message); } finally { setBusy(false); } }
  if (!token) return <Auth onLogin={setToken}/>;
  const currency = n => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n || 0);
  const competitorProducts = Object.values(analysis?.marketplace_products || {}).flat();
  const competitorPrices = competitorProducts.map(p => Number(p.price)).filter(p => Number.isFinite(p) && p > 0);
  const priceRange = competitorPrices.length ? { low: Math.min(...competitorPrices), high: Math.max(...competitorPrices) } : null;
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#"><span className="brand-mark">P</span> pricepulse</a><span className="nav-label">WORKSPACE</span><button className="nav-item active">◈ <span>Overview</span></button><button className="nav-item" onClick={() => setFormOpen(true)}>＋ <span>Add a product</span></button><div className="side-products"><span className="nav-label">YOUR PRODUCTS</span>{products.map(p => <button key={p.id} onClick={() => { setSelected(p); setAnalysis(null); }} className={`product-nav ${selected?.id === p.id ? 'chosen' : ''}`}><span className="product-dot"/>{p.product_name || `Product ${p.id}`}</button>)}</div><div className="side-bottom"><div className="user-avatar">{(selected?.product_name || 'P')[0]}</div><div className="user-meta"><b>My workspace</b><small>Price intelligence</small></div><button title="Sign out" className="logout" onClick={() => setToken('')}>↗</button></div></aside>
    <main className="main-area"><header className="topbar"><div><span className="breadcrumb">Workspace <b>/</b> Overview</span><h1>Pricing intelligence</h1></div><button className="user-pill" onClick={() => setToken('')}><span className="status-dot"/> Secure workspace <span>↗</span></button></header>
      {error && <div className="notice error-msg" role="alert">{error}<button onClick={() => setError('')}>×</button></div>}
      {!products.length ? <section className="empty-hero"><span className="empty-icon">✳</span><span className="eyebrow">YOUR FIRST MARKET READ</span><h2>Start with a product.<br/><i>Get a clearer price.</i></h2><p>Add your product details and PricePulse will map the competitive landscape and check a profit-aware price.</p><button className="primary" onClick={() => setFormOpen(true)}>Add your first product <span>↗</span></button></section> : <>
        <section className="welcome-row"><div><span className="eyebrow">MARKET PULSE · {new Date().toLocaleDateString('en-IN', { month: 'long', day: 'numeric', year: 'numeric' })}</span><h2>{selected?.product_name || 'Choose a product'}</h2><p className="muted">{selected?.category || 'Your pricing workspace'}{selected?.brand ? ` · ${selected.brand}` : ''}</p></div><button className="outline" onClick={() => setFormOpen(true)}>＋ Add product</button></section>
        <section className="summary-grid"><article className="recommend-card"><div className="card-top"><span className="eyebrow">PRICE RECOMMENDATION</span><span className="live-pill"><i/> {recommendation ? 'LATEST ANALYSIS' : 'AWAITING ANALYSIS'}</span></div>{recommendation ? <><strong className="price-value">{currency(recommendation.recommended_price)}</strong><p className="muted">Suggested selling price</p><div className="rec-divider"/><div className="rec-stats"><div><span>Expected margin</span><b>{Number(recommendation.profit_percentage || 0).toFixed(1)}%</b></div><div><span>Confidence</span><b>{recommendation.confidence_score ? `${Math.round(recommendation.confidence_score * 100)}%` : '—'}</b></div></div><p className="reason">{recommendation.reasoning}</p></> : <div className="card-empty"><span>✳</span><p>Run an analysis to see a recommendation grounded in your market and margin.</p><button className="primary" disabled={busy} onClick={analyze}>{busy ? 'Analyzing…' : 'Analyze pricing'} <span>↗</span></button></div>}</article>
          <article className="landscape-card"><div className="card-top"><span className="eyebrow">COMPETITIVE LANDSCAPE</span><span className="tiny-icon">⌁</span></div>{analysis?.marketplace_statuses ? <div className="market-list">{['Amazon','Flipkart','Myntra','Meesho'].map(name => <div className="market-row" key={name}><span className="market-brand">{name[0]}</span><b>{name}</b><span className={`market-status ${String(analysis.marketplace_statuses[name] || 'EMPTY').toLowerCase()}`}>{analysis.marketplace_statuses[name] || 'EMPTY'}</span></div>)}</div> : <div className="landscape-empty"><p>Competitor signals will appear after your first analysis.</p></div>}{priceRange && <div className="price-range"><div><span>Observed price range</span><b>{currency(priceRange.low)} – {currency(priceRange.high)}</b></div><div className="range-track"><i style={{ left: '4%', width: '92%' }}/></div><small>{competitorPrices.length} stored competitor observations</small></div>}<div className="landscape-foot"><span>Product cost</span><b>{currency(selected?.cost_price)}</b></div></article></section>
        <section className="workflow-section"><div className="section-heading"><div><span className="eyebrow">HOW THE SIGNAL BECOMES A PRICE</span><h3>Analysis workflow</h3></div><button className="text-action" disabled={busy} onClick={analyze}>{busy ? 'Working…' : 'Run analysis ↗'}</button></div><div className="workflow-track">{['IDENTITY','CATALOG','SCOUT','RAG','STRATEGIST','COMPLIANCE'].map((step, i) => { const state = analysis?.workflow?.find(s => s.step === step)?.status; return <div className={`workflow-step ${state === 'COMPLETED' ? 'done' : state === 'FAILED' ? 'failed' : ''}`} key={step}><span className="step-circle">{state === 'COMPLETED' ? '✓' : String(i + 1).padStart(2, '0')}</span><span>{step}</span>{i < 5 && <i className="step-line"/>}</div>; })}</div>{analysis?.compliance?.reasons?.length > 0 && <p className="warning-line">{analysis.compliance.reasons.join(' ')}</p>}{analysis?.warnings?.length > 0 && <p className="warning-line">{analysis.warnings.join(' ')}</p>}{analysis?.recommendation && <p className="success-line">Compliance approved the recommendation for display.</p>}</section>
        <section className="evidence-section"><div className="section-heading"><div><span className="eyebrow">EVIDENCE, NOT ESTIMATES</span><h3>Marketplace coverage</h3></div></div><div className="coverage-grid">{['Amazon','Flipkart','Myntra','Meesho'].map(name => { const status = analysis?.marketplace_statuses?.[name]; return <article className="coverage-item" key={name}><span className="market-brand">{name[0]}</span><div><b>{name}</b><small>{status === 'SUCCESS' ? 'Products found in this analysis' : status === 'BLOCKED' ? 'Marketplace unavailable for this analysis' : status ? 'No relevant products found' : 'Not analyzed yet'}</small></div><span className={`market-status ${(status || 'pending').toLowerCase()}`}>{status || 'PENDING'}</span></article>; })}</div>{competitorProducts.length > 0 && <div className="competitor-products"><h4>Products found</h4>{['Amazon','Flipkart','Myntra','Meesho'].map(name => (analysis?.marketplace_products?.[name] || []).map((item, index) => <div className="competitor-row" key={`${name}-${index}`}><span className="market-brand">{name[0]}</span><div><b>{item.product_name}</b><small>{name}{item.product_details ? ` · ${String(item.product_details).slice(0, 110)}` : ''}</small></div><strong>{currency(item.price)}</strong>{item.product_url && <a href={item.product_url} target="_blank" rel="noreferrer" aria-label={`Open ${item.product_name} at ${name}`}>↗</a>}</div>))}</div>}</section>
      </>}
    </main>
    <button className="chat-launch" aria-label="Open PricePulse assistant" onClick={() => setChatOpen(!chatOpen)}>✳</button>{chatOpen && <aside className="chat-panel"><div className="chat-head"><span className="chat-spark">✳</span><div><b>PricePulse assistant</b><small>Grounded in your product data</small></div><button onClick={() => setChatOpen(false)}>×</button></div><div className="chat-content"><div className="chat-bubble">Ask me about your product, market coverage, or latest price recommendation.</div>{answer && <div className="chat-bubble answer">{answer}</div>}</div><form className="chat-form" onSubmit={ask}><input value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask about this product…"/><button disabled={busy || !selected}>↗</button></form></aside>}
    {formOpen && <div className="modal-shade" onClick={() => setFormOpen(false)}><form className="product-modal" onSubmit={createProduct} onClick={e => e.stopPropagation()}><button type="button" className="modal-close" onClick={() => setFormOpen(false)}>×</button><span className="eyebrow">A BETTER READ STARTS HERE</span><h2>Tell us about your product.</h2><p className="muted">A few details help us find the right market signals.</p><div className="form-grid"><label className="full">Product name<input name="product_name" required placeholder="e.g. Botanical hair oil"/></label><label>Category<input name="category" placeholder="Hair care"/></label><label>Brand<input name="brand" placeholder="Your brand"/></label><label className="full">Product details<textarea name="details" rows="3" placeholder="Ingredients, use, size or other identifying details"/></label><label>Cost price (₹)<input name="cost" type="number" min="0.01" step="0.01" required placeholder="0.00"/></label><label>Stock quantity<input name="stock" type="number" min="0" step="1" required placeholder="0"/></label><label>Minimum profit margin (%)<input name="margin" type="number" min="0" step="0.1" required placeholder="15"/></label></div><button className="primary wide" disabled={busy}>{busy ? 'Saving product…' : 'Add product'} <span>↗</span></button></form></div>}
  </div>;
}

createRoot(document.getElementById('root')).render(<App/>);
